<?php

namespace FortyQ\SeoAssistant\Support;

use Spatie\Browsershot\Browsershot;
use WP_Error;
use function absint;
use function esc_url_raw;
use function function_exists;
use function get_permalink;
use function is_wp_error;
use function is_dir;
use function sanitize_text_field;
use function unlink;
use function wp_get_attachment_url;
use function wp_tempnam;

class SocialImageGenerator
{
    private const WIDTH = 1200;
    private const HEIGHT = 628;
    private const QUALITY = 70;

    /**
    * Generate a social image for a post, upload it to the Media Library, and persist TSF meta.
    */
    public function generate(int $postId, ?string $targetUrl = null): array|WP_Error
    {
        if (!class_exists(Browsershot::class)) {
            return new WP_Error(
                'seo_social_image_missing_dep',
                __('Unable to generate image: Browsershot is not installed.', 'radicle'),
                ['status' => 500]
            );
        }

        // Browsershot's launcher requires the Puppeteer JS package to be present.
        if (!$this->hasPuppeteerModule()) {
            return new WP_Error(
                'seo_social_image_puppeteer_missing',
                __('Puppeteer is not installed on this server. Install it (e.g., npm install puppeteer) or configure BROWSERSHOT_CHROME_PATH.', 'radicle'),
                ['status' => 500]
            );
        }

        $url = $targetUrl ?: get_permalink($postId);

        if (!$postId || !$url) {
            return new WP_Error(
                'seo_social_image_invalid',
                __('Missing post or URL to capture.', 'radicle'),
                ['status' => 400]
            );
        }

        if (!function_exists('wp_tempnam')) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        $tmp = wp_tempnam('seo-social-image');
        if (!$tmp) {
            return new WP_Error(
                'seo_social_image_tmp_failed',
                __('Could not create a temporary file for the social image.', 'radicle'),
                ['status' => 500]
            );
        }

        $tmpPath = $tmp . '.jpg';
        @rename($tmp, $tmpPath); // Make sure it ends with .jpg for media_handle_sideload.

        try {
            Browsershot::url($url)
                ->windowSize(self::WIDTH, self::HEIGHT)
                ->setScreenshotType('jpeg', self::QUALITY)
                ->waitUntilNetworkIdle()
                ->save($tmpPath);
        } catch (\Throwable $e) {
            @unlink($tmpPath);

            return new WP_Error(
                'seo_social_image_capture_failed',
                __('Unable to capture the social image.', 'radicle'),
                [
                    'status' => 500,
                    'detail' => $e->getMessage(),
                ]
            );
        }

        if (!file_exists($tmpPath)) {
            return new WP_Error(
                'seo_social_image_missing_file',
                __('Screenshot was not created.', 'radicle'),
                ['status' => 500]
            );
        }

        if (!function_exists('media_handle_sideload')) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
            require_once ABSPATH . 'wp-admin/includes/media.php';
            require_once ABSPATH . 'wp-admin/includes/image.php';
        }

        $fileArray = [
            'name' => 'social-image-' . $postId . '.jpg',
            'type' => 'image/jpeg',
            'tmp_name' => $tmpPath,
            'error' => 0,
            'size' => filesize($tmpPath) ?: null,
        ];

        $attachmentId = media_handle_sideload($fileArray, $postId, __('Social image generated by SEO Assistant', 'radicle'));

        if (is_wp_error($attachmentId)) {
            @unlink($tmpPath);

            return $attachmentId;
        }

        $url = wp_get_attachment_url($attachmentId);

        if (!$url) {
            @unlink($tmpPath);

            return new WP_Error(
                'seo_social_image_url_missing',
                __('Uploaded social image URL is missing.', 'radicle'),
                ['status' => 500]
            );
        }

        update_post_meta($postId, '_social_image_url', esc_url_raw($url));
        update_post_meta($postId, '_social_image_id', absint($attachmentId));

        return [
            'attachment_id' => $attachmentId,
            'url' => $url,
        ];
    }

    private function hasPuppeteerModule(): bool
    {
        // Project root: packages/40q/40q-seo-assistant/src/Support -> up 6 levels.
        $root = dirname(__DIR__, 6);
        $modulePath = $root . '/node_modules/puppeteer';

        // Allow users to point to a custom module path via env if needed.
        $customPath = getenv('PUPPETEER_MODULE_PATH');
        if ($customPath && is_dir($customPath)) {
            return true;
        }

        return is_dir($modulePath);
    }
}
